# Generated by Django 4.1.1 on 2022-10-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_back', '0002_databufer'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbacktests',
            name='max_open_trades',
            field=models.IntegerField(default=3, verbose_name='Max open trades:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allbacktests',
            name='my_stoploss_time',
            field=models.IntegerField(verbose_name='My Stop-loss time (after [n] min)'),
        ),
        migrations.AlterField(
            model_name='allbacktests',
            name='my_stoploss_value',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='My Stop-loss value (after [n] min)'),
        ),
    ]
