# Generated by Django 4.1.1 on 2022-10-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_back', '0005_allbacktests_buy_cci_allbacktests_sell_cci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allbacktests',
            name='arg_R',
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='buy_adx',
            field=models.IntegerField(default=True, verbose_name='Buy side: ADX between 20 and 50: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='buy_adx_enable',
            field=models.BooleanField(default=True, verbose_name='ADX buy enable: '),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='buy_fastd',
            field=models.IntegerField(default=True, verbose_name='Buy side: FastD between 15 and 45: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='buy_fastd_enable',
            field=models.BooleanField(default=True, verbose_name='FastD buy enable: '),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='buy_fastk',
            field=models.IntegerField(default=False, verbose_name='Buy side: FastK between 15 and 45: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='buy_fastk_enable',
            field=models.BooleanField(default=True, verbose_name='FastK buy enable: '),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='buy_mfi',
            field=models.IntegerField(default=True, verbose_name='Buy side: MFI between 10 and 25: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='buy_mfi_enable',
            field=models.BooleanField(default=True, verbose_name='MFI buy enable: '),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='sell_adx',
            field=models.IntegerField(default=False, verbose_name='Sell side: ADX between 50 and 100: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='sell_adx_enable',
            field=models.BooleanField(default=True, verbose_name='ADX sell enable: '),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='sell_cci_scalp',
            field=models.IntegerField(default=True, verbose_name='Sell side: CCI between 100 and 200: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='sell_cci_scalp_enable',
            field=models.BooleanField(default=True, verbose_name='CCI sell enable: '),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='sell_fastd',
            field=models.IntegerField(default=True, verbose_name='Sell side: FastD between 50 and 100: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='sell_fastd_enable',
            field=models.BooleanField(default=True, verbose_name='FastD sell enable: '),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='sell_fastk',
            field=models.IntegerField(default=True, verbose_name='Sell side: FastK between 50 and 100: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='sell_fastk_enable',
            field=models.BooleanField(default=True, verbose_name='FastK sell enable: '),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='sell_mfi',
            field=models.IntegerField(default=False, verbose_name='Sell side: MFI between 50 and 100: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='sell_mfi_enable',
            field=models.BooleanField(default=True, verbose_name='MFI sell enable: '),
        ),
        migrations.AlterField(
            model_name='allbacktests',
            name='arg_P',
            field=models.IntegerField(verbose_name='Price incriase in N candles (P)'),
        ),
        migrations.AlterField(
            model_name='allbacktests',
            name='hyperopt',
            field=models.BooleanField(default=False, verbose_name='Hyper opt'),
        ),
    ]
