# Generated by Django 4.1.1 on 2022-10-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_back', '0006_remove_allbacktests_arg_r_allbacktests_buy_adx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbacktests',
            name='arg_R',
            field=models.IntegerField(default=100, verbose_name='Persen of same candles (R)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allbacktests',
            name='arg_P',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Price incriase in N candles (P)'),
        ),
        migrations.AlterField(
            model_name='allbacktests',
            name='buy_fastk_enable',
            field=models.BooleanField(default=False, verbose_name='FastK buy enable: '),
        ),
        migrations.AlterField(
            model_name='allbacktests',
            name='sell_adx_enable',
            field=models.BooleanField(default=False, verbose_name='ADX sell enable: '),
        ),
        migrations.AlterField(
            model_name='allbacktests',
            name='sell_mfi_enable',
            field=models.BooleanField(default=False, verbose_name='MFI sell enable: '),
        ),
    ]
