# Generated by Django 4.1.1 on 2022-11-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_back', '0007_allbacktests_arg_r_alter_allbacktests_arg_p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbacktests',
            name='ema_signal_enable',
            field=models.BooleanField(default=False, verbose_name='EMA signal enable: '),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='ema_trend',
            field=models.IntegerField(default=50, verbose_name='EMA Trend, between 3 and 52: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='fast_len',
            field=models.IntegerField(default=12, verbose_name='Shorter-term period MA, between 2 and 51: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='slow_len',
            field=models.IntegerField(default=26, verbose_name='Longer-term period MA, between 3 and 52: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='sma_signal_enable',
            field=models.BooleanField(default=False, verbose_name='SMA signal enable: '),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='sma_source_enable',
            field=models.BooleanField(default=False, verbose_name='SMA source enable: '),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='source',
            field=models.CharField(default='close', max_length=50, verbose_name='Source of data:'),
            preserve_default=False,
        ),
    ]
