# Generated by Django 4.1.1 on 2022-12-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_back', '0008_allbacktests_ema_signal_enable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbacktests',
            name='loss_beepboop',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='Beep Boop Loss'),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='min_roi_beepboop',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='Beep Boop ROI:'),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='series_len_beepboop',
            field=models.IntegerField(default=4, verbose_name='Beep Boop Series length (T)'),
        ),
    ]
