# Generated by Django 4.1.1 on 2023-01-13 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_back', '0009_allbacktests_loss_beepboop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbacktests',
            name='start_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Strat data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='stop_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Stop data'),
            preserve_default=False,
        ),
    ]
