# Generated by Django 4.1.1 on 2023-01-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_back', '0012_alter_allbacktests_start_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbacktests',
            name='start_data',
            field=models.DateField(auto_now_add=True, verbose_name='Strat data'),
        ),
        migrations.AlterField(
            model_name='allbacktests',
            name='stop_data',
            field=models.DateField(auto_now_add=True, verbose_name='Stop data'),
        ),
    ]
