# Generated by Django 4.1.1 on 2023-01-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_back', '0013_alter_allbacktests_start_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbacktests',
            name='my_force_exit_time',
            field=models.IntegerField(default=0, verbose_name='My Force exit time (after [n] min)'),
        ),
        migrations.AddField(
            model_name='allbacktests',
            name='my_force_exit_value',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='My Force exit value (after [n] min)'),
        ),
        migrations.AlterField(
            model_name='allbacktests',
            name='start_data',
            field=models.DateField(verbose_name='Strat data'),
        ),
        migrations.AlterField(
            model_name='allbacktests',
            name='stop_data',
            field=models.DateField(verbose_name='Stop data'),
        ),
    ]
